backend = "glx";
shadow = false;
corner-radius = 10;
detect-rounded-corners = true;
detect-client-opacity = true;
no-fading-openclose = true;
unredir-if-possible = true;
unredir-if-possible-delay = 0;
