# /* ---- 💫 https://github.com/LinuxBeginnings 💫 ---- */  #
# /* wallust template - colors-kitty */

foreground         #D1D1D3
background         #0B0E20
cursor             #5F4A45

active_tab_foreground     #0B0E20
active_tab_background     #D1D1D3
inactive_tab_foreground   #D1D1D3
inactive_tab_background   #0B0E20

active_border_color   #D1D1D3
inactive_border_color #0B0E20
bell_border_color     #A59D8A

color0      #9D9DA1
color1		#A59D8A
color2		#9F827A
color3		#816964
color4		#7A5B55
color5		#452829
color6		#3C2229
color7		#635E53
color8		#9A9281
color9		#DCD1B8
color10		#D4ADA2
color11		#AC8C85
color12		#A27A71
color13		#5C3637
color14		#502D37
color15		#E5E0D3
